FROM nginx:1.29-alpine

ARG SERVER_NAME=_
ARG CLIENT_MAX_BODY_SIZE=10m

COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY . /var/www/html/

RUN rm -f /var/www/html/Dockerfile.nginx \
    /var/www/html/docker-compose.yml \
    /var/www/html/.env.example \
    /var/www/html/.gitignore \
    && chown -R nginx:nginx /var/www/html \
    && nginx -t

EXPOSE 80
