FROM nginx:1.29-alpine

COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY index.php privacy-policy.php terms-of-service.php ads.txt robots.txt 404.html /var/www/html/
COPY assets /var/www/html/assets/

RUN chown -R nginx:nginx /var/www/html

EXPOSE 80